## Ana Paula

In [9]:
import pandas as pd  
# 1. Carga del dataset
df = pd.read_csv(r'data\Teen_Mental_Health_Dataset.csv')
# 2. Visualizar las primeras 5 filas
print("--- Primeras filas del dataset ---")
display(df.head())

# 3. Inspección de tipos de datos y valores no nulos
print("\n--- Información general del DataFrame ---")
df.info()

--- Primeras filas del dataset ---

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

--- Información general del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [8]:
# 1. Comprobar y eliminar duplicados
duplicados = df.duplicated().sum()
print(f"Filas duplicadas detectadas: {duplicados}")

if duplicados > 0:
    df.drop_duplicates(inplace=True)
    print("¡Duplicados eliminados!")

Filas duplicadas detectadas: 0

In [10]:
# Comprobar los valores únicos exactos de las columnas categóricas
print("Valores únicos en 'gender':")
print(df['gender'].unique())

print("\nValores únicos en 'platform_usage':")
print(df['platform_usage'].unique())

print("\nValores únicos en 'social_interaction_level':")
print(df['social_interaction_level'].unique())

Valores únicos en 'gender':
['male' 'female']

Valores únicos en 'platform_usage':
['Instagram' 'TikTok' 'Both']

Valores únicos en 'social_interaction_level':
['low' 'high' 'medium']

In [11]:
# 1. Codificación Ordinal para 'social_interaction_level'
mapa_niveles = {'low': 0, 'medium': 1, 'high': 2}
df['social_interaction_level'] = df['social_interaction_level'].map(mapa_niveles)

# 2. Codificación One-Hot para 'gender' y 'platform_usage'
# Usamos drop_first=True para evitar la "trampa de la multicolinealidad" en regresión
df = pd.get_dummies(df, columns=['gender', 'platform_usage'], drop_first=True, dtype=int)

# 3. Comprobar cómo ha quedado el dataset
print("--- Estructura del dataset codificado ---")
df.info()
print("\n--- Primeras filas transformadas ---")
display(df.head())

--- Estructura del dataset codificado ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   daily_social_media_hours  1200 non-null   float64
 2   sleep_hours               1200 non-null   float64
 3   screen_time_before_sleep  1200 non-null   float64
 4   academic_performance      1200 non-null   float64
 5   physical_activity         1200 non-null   float64
 6   social_interaction_level  1200 non-null   int64
 7   stress_level              1200 non-null   int64
 8   anxiety_level             1200 non-null   int64
 9   addiction_level           1200 non-null   int64
 10  depression_label          1200 non-null   int64
 11  gender_male               1200 non-null   int64
 12  platform_usage_Instagram  1200 non-null   int64
 13  platform_usage_TikTok     1200 non-null   int64
dtypes: float64(5), int64(9)
memory usage: 131.4 KB

--- Primeras filas transformadas ---

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok
0,14,7.9,7.4,2.9,3.01,1.5,0,2,2,1,0,1,1,0
1,19,1.9,8.0,2.9,3.22,0.8,2,8,1,10,0,0,0,1
2,17,1.3,7.6,0.5,3.92,0.0,2,2,4,2,0,0,1,0
3,15,7.4,6.9,1.6,3.48,0.8,1,1,7,9,0,1,0,1
4,15,4.7,4.9,3.0,2.37,1.4,1,3,5,2,0,0,0,0